#Site configuration
title: "Jie Gao - UPenn PhD Student"
name:  Jie Gao
author: Jie Gao
work:  Ph.D. Student<br/>University of Pennsylvania
year: 2019

# Navigation
nav1: "About Me"
nav2: "Education"
nav3: "Work Experience"
nav4: "Teaching"
nav5: "Publications"
# nav6: "Current Research"

email: jiegao@seas.upenn.edu
address: 3401 Walnut St Rm 464C<br/>Philadelphia PA, 19104
