#Site configuration
title: "Jie Gao - UPenn PhD Student"
name:  Jie Gao
author: Jie Gao
work:  Ph.D. Student<br/>University of Pennsylvania
year: 2019

# Navigation
nav1: "About Me"
nav2: "Education"
nav3: "Work Experience"
nav4: "Teaching"
nav5: "Publications"
nav6: "Current Research"


# Section1
sec1: "About Me"
sec2: "Third-year PhD student at University of Pennsylvania."
sec3: "My area of study is Natural Language Processing, with focus in Machine Translation."

# Section 2
sec4: "Education"
sec5: "I have received education in Computer Science."

sec31: "Work Experience"

# Section 3
sec41: "Teaching"
sec7: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec8: "Possibly broke spacetime"
sec9: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec10: "Terraformed a small moon"
sec11: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec12: "Snapped dark matter in the wild"
sec13: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."


sec51: "Publications"


sec61: "Current Research"


# Social Links
facebook: gao.jie.7737
#twitter:  username
#google: jiegao1991@gmail.com
#instagram: username
#pinterest: username
#linkedin: username
#youtube: username
#spotify: username
#lastfm: username
#github: betapoc
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: jiegao@seas.upenn.edu
address: 3401 Walnut St Rm 464C<br/>Philadelphia PA, 19104
